# Alembic Configuration
[alembic]
script_location = alembic
file_template = %%(year)d_%%(month)02d_%%(day)02d_%%(hour)02d%%(minute)02d-%%(rev)s_%%(slug)s
prepend_sys_path = src
sqlalchemy.url = sqlite:///storage/dev_database.db

[post_write_hooks]

[logging]
default_level = INFO
